server:
  port: 8080
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-type: PKCS12
    key-password: megumin123@
    key-store-password: megumin123@


cloud:
  aws:
    credentials:
      session-token: FwoGZXIvYXdzEKf//////////wEaDDo/jB84pVITDyKp2iK6AVj4Qbyr9qLiYOuJkHmt+H/c5Rn5fkCP3jmsMT44xbG/t1kxdRn7HAlR9wM1znPSRg6l/SyBY65+yn02k7SWWFpSsQNEtfCJ+cFRYwZDbWhNDFu2xkj2LcBbnKFtPt7KVhOdI8TL9BPAkHDcXTcLmr89xMeDQYN+zetlQYuwNWuizGwGSE4FCqx4UzC7rM9fV4i8EZH1+cUBXqATJchfEKX9I9aG9tzuNGHxDjPnPdXdYNMBKvUYkURg4ijVh4WiBjItOYGIdZAcJKRV1KSSROtPL3+UbLHB3eLqOiWL6UsID0mbCNZrP0I4UWU67FQj
      access-key: ASIAWYIBPFHG3ALWCRVC
      secret-key: cG3KivpwWGEZu6CZZlprEv6jWbAIiCJfFCXTr1Wk
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: meguminpaulista

spring:
  profiles:
    active:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 6MB
      max-request-size: 10MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  logging:
    pattern:
      console: "%d %-5level %logger : %msg%n"
    level:
      org.springframework: info
      org.hibernate: debug
