server:
  port: 8080

cloud:
  aws:
    credentials:
      session-token: FwoGZXIvYXdzENn//////////wEaDDllJDF7agFmwp5TsyK6AR+pVJnSGfG1aEQCYYRde3FuHW4SSUSPQFUOa7mnI88awQ+GdWSWkIKyMf7PEoB/mBv1z/BaTDnZbg/Z97+QOlsg4zqPUcXuurl+kxaP5IP0fQLeGBSX7TgxC/30zokj9j+IHhtEHzDwbKF1bjbUItQr16eVnbCyFwPPTe10qvxXbYhbBPP6tFfask/AbAFQkCYjsXdikDCfYzaiFOEfZWYuVg6YvQnTyy5vMROSzgdmyCoiddjtfpI6OSiEvoCjBjItkN68CQp091h4pLfcgmaRYBGu7X0n53xGZhEKdrdKn4ABIBJFyoBZzd+EpNMd
      access-key: ASIAWYIBPFHGSNR36M4U
      secret-key: rYa+pIa82uHJRUUDP2L31LvA3YBJ7yhWlKMKi+yX
    region:
      static: us-east-1
    stack:
      auto: false

application:
  security:
    jwt:
      secret-key: 34753778214125442A472D4A614E645267556B58703273357638792F423F4528
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  bucket:
    name: meguminpaulista

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 6MB
      max-request-size: 10MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://54.163.233.38:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  logging:
    pattern:
      console: "%d %-5level %logger : %msg%n"
    level:
      org.springframework: info
      org.hibernate: debug
